### ISSUE TITLE
Will you be updating soon

### ISSUE THREAD

**Issue by tinjaw** [pistell/MGRS-Mapper#7]
I was going to start spending some time on this project. However, the readme says...

This repo contains the old version of the app. It will however work if you clone it and install it yourself.

I would rather get access to the latest and greatest version. Will you be committing those recent changes to this repo? Maybe in an experimental branch?

**Comment by pistell** [comment]
Hey tinjaw,
Sorry for the late response. The current version of the application shares almost no DNA with the old version. I did a complete rewrite of everything. I made my own MGRS grid overlay and my own symbol generator class. I lost my job during the Coronavirus and decided to turn this into a paid SaaS application. If you would like access to the production repository we can discuss this over email

**Comment by tinjaw** [comment]
I replied in a private email.
